.travis.yml, config.go, config_test.go, db.go, db_test.go, docker/create-and-setup-containers.sh, docker/create-containers.sh, docker/destroy-container.sh, migrations.go, migrations_test.go, migrator.go, test/create-test-tenants.sql, test/migrations/public/201602160001.sql, test/migrations/public/201602160004.sql, test/migrations/ref/201602160004.sql, test/migrations/tenants/201602160002.sql, test/migrations/tenants/201602160003.sql, test/migrations/tenants/201602160004.sql, test/migrator-postgresql.yaml.travis, test/migrator-test.yaml, test/migrator.yaml
First integration tests postgresql.
Locally use this:
```
$ docker/create-and-setup-containers.sh
$ go test -v
```
Or see `.travis.yml` to see how it's done on Travis.
=> Integration tests postgresql

.gitignore, README.md, docker/mariadb-create-and-setup-container.sh, docker/mariadb-destroy-container.sh, test/migrator.yaml
added mariadb docker scripts & example in README.md
=> added mariadb docker & example in README.md

.gitignore, db.go, db_mysql.go, db_postgresql.go, db_test.go, migrations.go, migrator.go, test/migrator-mysql.yaml, types.go
second part of refactoring (not the last one):
* created basic inheritance for DB connectors
* some additional cleanup
=> second part of refactoring

config/config.go, config/config_test.go, test/migrator-test-envs.yaml
added support for reading config properties also from env variables
=> added support for reading config properties also from env variables

README.md, config/config.go, config/config_test.go, migrator.go, notifications/notifications.go, notifications/notifications_slack.go, server/server.go, server/server_mocks.go, server/server_test.go, test/migrator-test-envs.yaml, xcli/xcli.go, xcli/xcli_test.go
notification tests to come in separate pull request
=> added server mode and slack notifications, code cleanup

config/config.go, config/config_test.go, coverage.sh, db/db.go, db/db_mysql.go, db/db_postgresql.go, loader/disk_loader.go, loader/disk_loader_test.go, loader/loader.go, migrations/migrations.go, migrator.go, notifications/notifications.go, notifications/notifications_slack_test.go, notifications/notifications_test.go, server/server.go, server/server_mocks.go, test/migrator-test-envs.yaml, types/types.go, utils/utils.go, xcli/xcli.go, xcli/xcli_mocks.go, xcli/xcli_test.go
added notifications tests, code style fixes (golint)
=> added notifications tests, code style fixes (golint)

test/performance/generate-test-migrations.sh, test/performance/test.sh
Simple test framework which allows to test performance of migrator.
Resolves #15.
=> simple test framework which allows to test performance of migrator

config/config.go, config/config_test.go, db/db.go, db/db_test.go, loader/disk_loader.go, migrator.go, server/server.go, server/server_test.go, types/types.go, types/types_test.go, xcli/xcli.go, xcli/xcli_test.go
reworked how logging is done, now uses golang log to output all text, added new information as requested in #17.
Resolves #17.
=> reworked how logging is done

core/core.go, core/core_mocks.go, core/core_test.go, migrator.go, server/server.go
Reworked xcli module to core.
Resolves #20.
=> reworked xcli module to core

db/db.go, db/db_mysql.go, db/db_postgresql.go, db/db_test.go, docker/mysql-create-and-setup-container.sh, migrator.go, server/server.go, test/migrator-mysql.yaml, test/migrator-mysql.yaml.travis
Switched to new MySQL driver which supports executing bulk SQL commands which is much better in terms of performance.
During local tests it showed an improvement of a factor of 10.
=> switched to new MySQL driver which supports executing bulk SQL commands

README.md, migrations/migrations.go, test/performance/generate-test-migrations.sh
Extending performance test generator and adding performance tests results to README.md.
Resolves #22.
=> extending performance test generator

config/config.go, config/config_test.go, migrations/migrations.go, server/server.go, server/server_test.go, test/migrator-overrides.yaml
Pull request contains: 
* moved default port to server module
* formatting fixes from gofmt
Resolves #18.
=> moved default port to server module

README.md, config/config.go, config/config_test.go, core/core.go, core/core_mocks.go, db/db.go, db/db_mysql.go, db/db_postgresql.go, db/db_test.go, migrations/migrations.go, migrations/migrations_test.go, migrator.go, server/server.go, server/server_mocks.go, server/server_test.go, test/migrations/tenants/201602160002.sql, test/migrator-overrides.yaml, test/migrator-test-envs.yaml, test/migrator-test.yaml
This pull apart of adding new tenant functionality contains changes to variable naming conventions (minor but generated a lot of changes in the project).
Resolves #21.
=> Adding new tenant functionality

test/performance/generate-test-migrations.sh
added creating schema in the first perf test migration
=> added creating schema in the first perf test migration

README.md, docker/create-and-setup-container.sh, docker/scripts/mysql-create-and-setup-container.sh, docker/scripts/postgresql-create-and-setup-container.sh, test/performance/generate-test-migrations.sh
pull contains:
* perf test generator enhancements (works with flyway now)
* docker scripts updates
* updated README.md
=> perf test generator enhancements, docker scripts updates

README.md, db/db.go, db/db_dialect.go, db/db_mysql.go, db/db_postgresql.go, db/db_test.go, server/server.go, server/server_test.go
Pull contains:
* added support for dialects to separate all SQL-flavours/DB-specific SQL commands
* additional: gofmt fixes for server module
=> Introduced dialects to separate SQL-flavours/DB-specific SQL commands

README.md, db/db.go, db/db_dialect.go, db/db_mssql.go, db/db_mysql.go, db/db_postgresql.go, db/db_test.go, docker/create-and-setup-container.sh, docker/scripts/mssql-create-and-setup-container.sh, test/create-test-tenants-mssql.sql, test/create-test-tenants.sql, test/migrations/public/201602160001.sql, test/migrations/tenants/201602160002.sql, test/migrator-mssql.yaml
This pull contains:
* Implementation of MSSQL
* reworked and extracted a lot of functionality from previous Connector to Dialect interfaces
* MySQL and PostgreSQL share most of BaseDialect interface methods
Resolves #36.
=> Implementation of MSSQL

README.md
prettifying README.md by using sql and yaml for code blocks and also, hoping that coveralls will detect a push to master and will finally start showing code coverage...
=> prettifying README.md by using sql and yaml for code blocks

.gitignore, .travis.yml, README.md, coverage.sh
=> Added codecov integration

README.md, db/db.go
goreport integration added, fixed spelling pointed out by go report service
=> goreport integration added

core/core.go, core/core_mocks.go, core/core_test.go, coverage.sh, db/db.go, db/db_dialect.go, db/db_mssql.go, db/db_mysql.go, db/db_postgresql.go, db/db_test.go, loader/disk_loader.go, loader/disk_loader_test.go, migrations/migrations.go, migrations/migrations_test.go, server/server.go, server/server_mocks.go, server/server_test.go, test/docker/scripts/mysql-create-and-setup-container.sh, test/migrations/config/201602160001.sql, test/migrations/config/201602160002.sql, test/migrations/public/201602160004.sql, test/migrations/ref/201602160003.sql, test/migrations/ref/201602160004.sql, test/migrations/tenants/201602160002.sql, test/migrations/tenants/201602160004.sql, test/migrations/tenants/201602160005.sql, types/types.go, utils/utils.go, utils/utils_test.go
Verify migrations action implemented. Pull request contains:
* verify migrations action - called for every apply and add tenant action (both in tool and server mode)
* storing contents and checksums in DB
* merged internal Migration and MigrationDefinition structs into one
* reworked sample migrations so that it uses syntax understandable by PostgreSQL, MSSQL, and MySQL
=> Verify migrations action

.travis.yml, README.md, config/config_test.go, core/core.go, core/core_mocks.go, core/core_test.go, coverage.sh, db/db.go, db/db_dialect.go, db/db_mssql.go, db/db_mysql.go, db/db_postgresql.go, db/db_test.go, loader/disk_loader.go, loader/disk_loader_test.go, loader/loader.go, notifications/notifications_slack.go, notifications/notifications_slack_test.go, notifications/notifications_test.go, server/server.go, server/server_mocks.go, server/server_test.go, ultimate-coverage.sh
Better error handling, db mock, changes in internal API.
Once merged into master this pull will be released v2.2.
=> Better error handling, db mock, changes in internal API

Dockerfile, README.md, TestDockerfile
cosmetic docker changes and updated readme
=> cosmetic docker changes and updated readme

Dockerfile, TestDockerfile, hooks/build
correct docker cloud integration - added git checkout to switch to correct branch as go get always fetches master
=> correct docker cloud integration

README.md, loader/disk_loader.go, loader/disk_loader_test.go, test/docker/scripts/mysql-create-and-setup-container.sh, utils/utils.go, utils/utils_test.go
Pull contains:
* implemented support for both relative and absolute paths in `baseDir`
* changes to README.md documentation
=> implemented support for both relative and absolute paths

Dockerfile, TestDockerfile
upgraded alpine and go containers
=> upgraded alpine and go containers

README.md, config/config.go, config/config_test.go, coordinator/coordinator.go, coordinator/coordinator_test.go, db/db.go, db/db_error_handling_test.go, migrator.go, notifications/notifications_test.go, setup.sh, test/migrator-mssql.yaml, test/migrator-mysql.yaml, test/migrator-mysql.yaml.travis, test/migrator-postgresql.yaml, test/migrator-postgresql.yaml.travis, test/migrator-test-envs.yaml, test/migrator-test.yaml
documentation updated to contain more examples and new v4.0 features, also contains some bug fixes detected while preparing the updated documentation.
=> Documentation update

server/server.go, server/server_test.go, types/types.go
implemented support for response type: summary or full
=> implemented support for response type: summary or full

README.md, config/config_test.go, coordinator/coordinator.go, coordinator/coordinator_mocks.go, coordinator/coordinator_test.go, db/db.go, db/db_error_handling_test.go, db/db_test.go, server/server.go, server/server_mocks.go
implemented support for **dry-run** and **sync** modes for `ApplyMigrations()` and `AddTenantAndApplyMigrations()`
=> Implement support for mode

README.md, hooks/build, migrator.go, server/server.go, server/server_test.go, types/types.go
migrator will introduce itself a little bit better on GET /
=> migrator will introduce itself a little bit better on GET /

README.md, contrib/aws-ecs-ecr-secretsmanager-rds-s3/README.md, contrib/kubernetes-aws-eks/README.md, contrib/kubernetes-aws-eks/alb-ingress-controller.yaml, contrib/kubernetes-aws-eks/kustomization.yaml, contrib/kubernetes-aws-eks/migrator-deployment.yaml, contrib/kubernetes-aws-eks/migrator-ingress.yaml, contrib/kubernetes-aws-eks/migrator-service.yaml, contrib/kubernetes-aws-eks/migrator.yaml
New documentation - running migrator on AWS EKS
=> New documentation - running migrator on AWS EKS

README.md, contrib/azure-aks/Dockerfile, contrib/azure-aks/README.md, contrib/azure-aks/kustomization.yaml, contrib/azure-aks/migrator-deployment.yaml, contrib/azure-aks/migrator-ingress.yaml, contrib/azure-aks/migrator-service.yaml, contrib/azure-aks/migrator.yaml, loader/azureblob_loader_test.go
added tutorial how to deploy migrator to Azure AKS
=> added tutorial how to deploy migrator to Azure AKS

.travis.yml, db/db.go, db/db_dialect.go, db/db_error_handling_test.go, db/db_postgresql.go, db/db_postgresql_test.go, db/db_test.go
Added versions API and PostgreSQL impl
Pending impls: MySQL and MSSQL.
=> added versions API and PostgreSQL impl

.travis.yml, db/db.go, db/db_dialect.go, db/db_error_handling_test.go, db/db_mysql.go, db/db_mysql_test.go, db/db_postgresql.go, db/db_postgresql_test.go, db/db_test.go
mysql impl of migrator versions
=> mysql impl of migrator versions

db/db.go, db/db_dialect.go, db/db_mssql.go, db/db_mssql_test.go, db/db_mysql.go, db/db_mysql_test.go, db/db_postgresql.go, db/db_postgresql_test.go
MS SQL versions API implementation
=> MS SQL versions API implementation

coordinator/coordinator.go, coordinator/coordinator_mocks.go, data/graphql.go, data/graphql_mocks.go, data/graphql_test.go, db/db.go, db/db_dialect.go, db/db_dialect_test.go, db/db_mssql.go, db/db_mssql_test.go, db/db_mysql.go, db/db_mysql_test.go, db/db_postgresql.go, db/db_postgresql_test.go, db/db_test.go, server/server_mocks.go, server/server_test.go, types/types.go
implemented getting versions for all dialects, extended  Connector and Coordinator interfaces, finally added first GraphQL versions queries
=> Versions in GraphQL

coordinator/coordinator.go, coordinator/coordinator_mocks.go, coordinator/coordinator_test.go, data/graphql.go, data/graphql_mocks.go, data/graphql_test.go, db/db.go, db/db_dialect.go, db/db_dialect_test.go, db/db_error_handling_test.go, db/db_mssql.go, db/db_mssql_test.go, db/db_mysql.go, db/db_mysql_test.go, db/db_postgresql.go, db/db_postgresql_test.go, db/db_test.go, server/server.go, server/server_mocks.go, server/server_test.go, types/types.go
implemented versions methods returning migrator versions together with db migrations
=> Versions and db migrations in graphql

contrib/azure-aks/README.md
updated Azure AKS README.md with production recommendations
=> updated Azure AKS README.md with production recommendations

db/db_postgresql.go, db/db_postgresql_test.go
=> posgresql-ddl

.github/workflows/codeql-analysis.yml
Adds github CodeQL Analysis workflow.
=> add codeql-analysis.yml

README.md, codecov.yml, config/config.go, config/config_test.go, coordinator/coordinator.go, coordinator/coordinator_mocks.go, db/db.go, go.mod, go.sum, notifications/notifications.go, notifications/notifications_test.go, types/types.go
More powerful webhooks - can customise the payload by providing a template in migrator config
=> More powerful webhooks

.github/workflows/docker-image.yml, .travis.yml, CONTRIBUTING.md, README.md, test/docker-compose.yaml, test/http-integration-tests.sh, test/migrator-dev/Dockerfile, test/migrator-docker.yaml
this pull contains documentation update for the upcoming v2021.0.0 release
=> documentation update for v2021.0.0

Dockerfile, hooks/build, hooks/post_push
Simplify Docker hub workflows and builds.
Bigger picture: automate as much as I can new migrator releases (including automerges for dependabot pull requests).
=> simplify Docker hub workflows and builds

.github/dependabot.yml
switching back to daily dependabot checks but with different times to reduce number of required rebases
=> switching back to daily dependabot checks

.github/workflows/build.yml, .github/workflows/dependabot-pr.yml
adding back github actions build with pull_request_target event
=> adding back github actions build with pull_request_target event

.travis.yml
=> travis ci update

.gitignore, README.md, config/config_test.go, loader/disk_loader.go, loader/s3_loader.go, loader/s3_loader_test.go, test/migrator-test-envs.yaml
s3 baseLocation now supports optional prefixes for nested buckets
=> s3 baseLocation now supports optional prefixes for nested buckets

.gitignore, README.md, loader/azureblob_loader.go, loader/azureblob_loader_test.go
implemented support for optional prefixes for Azure Blob Container loader implementation
=> implemented support for optional prefixes for Azure Blob Container

.github/workflows/codeql-analysis.yml, .github/workflows/docker-image.yml, .github/workflows/docker-publish.yml, coordinator/coordinator_test.go, test/migrator-dev/Dockerfile, tutorials/aws-ecs/README.md
renamed branch to main, updated existing actions, added new docker publish action (as Docker autobuilds are no longer free)
=> renamed branch to main, updated existing actions, added new docker publish action

.github/workflows/docker-publish.yml
=> added correct docker hub envs

.github/workflows/docker-publish.yml
removed tags input as metadata-actions was erroring
=> removed tags input as metadata-actions was erroring

.github/workflows/docker-publish.yml
added missing tags input for event branch
=> added missing tags input for event branch

.github/workflows/build.yml, .github/workflows/dependabot-build.yml, .github/workflows/dependabot-pr.yml
another attempt at integrating automatic dependabot PR merges
=> another attempt at integrating automatic dependabot PR merges

.github/workflows/docker-publish.yml
don't publish branches, only tags and main as edge
=> don't publish branches, only tags and main as edge

PERFORMANCE.md, README.md, test/performance/create-test-tenants.sh, test/performance/flyway.conf, test/performance/flywaydb-test.sh, test/performance/generate-test-migrations.sh, test/performance/migrator-performance.yaml, test/performance/test.sh
Updating performance benchmark and its documentation
=> Updating performance benchmark and its documentation

.github/workflows/build.yml, .travis.yml, README.md, db/db_integration_test.go, test/docker-compose-dbs-only.yaml, test/docker-compose-it.yaml, test/http-integration-tests.sh, test/migrator-mariadb.yaml, test/migrator-percona.yaml
Integration testing only main db flavours. Other MySQL and PostgreSQL flavours are tested as a part of integration tests by their drivers.
=> Integration testing only main db flavours

PERFORMANCE.md, test/performance/liquibase-changelog.xml, test/performance/liquibase-test.sh, test/performance/liquibase.properties
pull requests contains:
- added performance tests and results for liquibase
- corrected times for migrator and flyway 10k migration tests (not 1k as previously)
=> added performance tests and results for liquibase

README.md, coordinator/coordinator.go, coordinator/coordinator_mocks.go, coordinator/coordinator_test.go, loader/azureblob_loader.go, loader/azureblob_loader_test.go, loader/disk_loader.go, loader/disk_loader_test.go, loader/loader.go, loader/s3_loader.go, loader/s3_loader_test.go
This pull requests contains continuation of work started in #285 
- loader checks implemented
- extended coordinator logic to cover loader checks as well
- updates to documentation
=> Loader health checks

README.md, common/common.go, common/common_test.go, config/config.go, config/config_test.go, db/db.go, loader/s3_loader.go, notifications/notifications_test.go, server/server.go, server/server_mocks.go, server/server_test.go
Enhancements to logging:
- added support for `logLevel` configuration property, it is optional and defaults to INFO
- unified graphql and migrator error responses in server module
- added more coverage in server module
=> Enhancements to logging
